### ISSUE TITLE
Dependencies not installed

### ISSUE THREAD

**Issue by CHJ85** [Murasan201/paperspace-automatic1111#3]
Hi there. One error that keeps showing up, preventing ControlNet from working is annotator.util. How do I fix this error?

```
*** Error loading script: api.py
    Traceback (most recent call last):
      File "/notebooks/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/api.py", line 11, in <module>
        from scripts import external_code, global_state
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 5, in <module>
        from scripts import global_state
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 8, in <module>
        from scripts.processor import *
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 4, in <module>
        from annotator.util import HWC3
    ModuleNotFoundError: No module named 'annotator.util'

---
*** Error loading script: batch_hijack.py
    Traceback (most recent call last):
      File "/notebooks/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 7, in <module>
        from scripts import external_code
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 5, in <module>
        from scripts import global_state
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 8, in <module>
        from scripts.processor import *
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 4, in <module>
        from annotator.util import HWC3
    ModuleNotFoundError: No module named 'annotator.util'

---
*** Error loading script: controlnet.py
    Traceback (most recent call last):
      File "/notebooks/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 13, in <module>
        from scripts import global_state, hook, external_code, processor, batch_hijack, controlnet_version, utils
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 8, in <module>
        from scripts.processor import *
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 4, in <module>
        from annotator.util import HWC3
    ModuleNotFoundError: No module named 'annotator.util'

---
2023-08-04 22:25:21,102 - ControlNet - INFO - ControlNet v1.1.236
*** Error loading script: external_code.py
    Traceback (most recent call last):
      File "/notebooks/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 5, in <module>
        from scripts import global_state
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 8, in <module>
        from scripts.processor import *
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 4, in <module>
        from annotator.util import HWC3
    ModuleNotFoundError: No module named 'annotator.util'

---
*** Error loading script: global_state.py
    Traceback (most recent call last):
      File "/notebooks/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 8, in <module>
        from scripts.processor import *
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 4, in <module>
        from annotator.util import HWC3
    ModuleNotFoundError: No module named 'annotator.util'

---
*** Error loading script: processor.py
    Traceback (most recent call last):
      File "/notebooks/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 4, in <module>
        from annotator.util import HWC3
    ModuleNotFoundError: No module named 'annotator.util'


```

**Comment by CHJ85** [comment]
Actually never mind.  Turns out, I tried to install the nightly build of ControlNet. Installing the stable one solved the issue.
